services:
  - type: web
    name: kiambu-house-hunter
    env: python
    runtime: python-3.12  # Specify Python 3.12
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: API_KEY
        sync: false
